# Generated by Django 3.0.7 on 2022-08-08 19:05

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20220710_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
